### PR TITLE
Frontend v1

### PR DESCRIPTION
**Pull request by jpdefrutosSINTEF**

### CODE REVIEW

**Comment by smistad** [comment]
Very nice start, but there are some issues: I can only see half the WSI, the scrolling seems to be disabled and some text is overlapping.
I also think we have to minimize the size of the top bar in order to get as much room for the WSI viewer as possible. This requires a small logo for the top, we can have the large logo at the frontpage and/or bottom instead I think. Maybe like the top bar/menu here: https://fast.eriksmistad.no/

**Comment by jpdefrutosSINTEF** [comment]
Thanks for the feedback. I'll work on it

**Comment by jpdefrutosSINTEF** [comment]
Solved the conflict on base.htm with master branch

**Comment by smistad** [comment]
@jpdefrutosSINTEF I fixed WSI not showing up. The reason for the bug is that if height is 100% of the canvas, it must have space to grow in the parent divs. Haven't checked multiple browsers and other content.

**Pull request merged**
