### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ingridtv**
This update includes many changes. E.g.:
- New question types (one-to-one sorting, click questions, free text)
- Bounding box annotation type
- Updated task functionality (select task type and more annotation options when making task)
- Updated look of the slide image viewer (e.g. hiding the slide info card, option to toggle annotations)

Can you please review this? In particular:
- See if you find errors/bugs
- Should we do any design/interface work before merging these or just put this on our to do-list?
- Any other feedback?

### CODE REVIEW

**Comment by ingridtv** [comment]
Here are some to do's that I see:

### Questions
- [ ] Should remove *Next task* button as long as only multiple choice questions are included in the pool of tasks that are looped through

#### One-to-one sorting
- [ ] Feedback to the user is only given as coloured alternatives. Should give feedback with symbols/text as well (for accessibility reasons)

#### Click question
- [ ] Remove text input from annotations in the click questions
- [ ] Since double-click is used for answering the click questions, this action should not zoom the WSI
- [ ] The *Show solution* button on the click question should maybe toggle annotations off, as well as on?

#### Free text question
- [ ] Clicking *Submit* with emtpy text box reloads the page, but doesn't give any feedback to the user (e.g. "You haven't answered the question"). Maybe the button should say "Check answer" or "Display teacher's solution" and the given text solution should be displayed even if no text was answered?


### Course
- [ ] Add styling/colour to the currently selected course tab
- [ ] Editing task from course should direct you back to the course, not to task list

**Comment by ingridtv** [comment]
The following TODO's from above have been skipped for now, but are added to the project board to be handled later:
Here are some to do's that I see:

- [ ] **One-to-one sorting**: Feedback to the user is only given as coloured alternatives. Should give feedback with symbols/text as well (for accessibility reasons)
- [ ] **Click question**: Since double-click is used for answering the click questions, this action should not zoom the WSI
- [ ] **Free text question**: Clicking *Submit* with emtpy text box reloads the page, but doesn't give any feedback to the user (e.g. "You haven't answered the question"). Maybe the button should say "Check answer" or "Display teacher's solution" and the given text solution should be displayed even if no text was answered?

**Review by UteSpiske — APPROVED** [review]
Seems good to me.

**Comment by ingridtv** [comment]
Okay, I'll merge this now

**Pull request merged**
