### PR TITLE
Task Type: Many-to-one

### PR DESCRIPTION
**Pull request by UteSpiske**
Hi, 
Could you please check the many-to-one task before merging it.
Also, the next button is back for the tasks and a feedback to the user that he/she needs to enter text before the optimal teacher solution is displayed in the click question.

### CODE REVIEW

**Comment by ingridtv** [comment]
I also think the "do" page should get at least a little bit of styling. Right now it's really hard to understand where I am allowed to drag things and not.

The list of options for the many-to-one task has an empty space. Does this have something to do with how you render the fields? I think the blank space (in green in the image below) might have come from one of the columns that are missing the blank space to drag things into (marked in red)
image

**Comment by ingridtv** [comment]
I see you're not using the CrispyForms anywhere - maybe it was tested when implementing the functionality? If it's not used, we should remove it from the requirements (and any imports)

**Comment by ingridtv** [comment]
I really like the feedback with check marks and X's, it's very visual and helpful! (A lot of small comments and updates here, my apologies!)

**Comment by UteSpiske** [comment]
It think these are good suggestions. 
Would be nice if you could add them.

**Review by ingridtv — APPROVED** [review]
I think we have resolved the comments, so I say this is ready to merge👍

**Pull request merged**
