### PR TITLE
Image browser search, filtering & redesign

### PR DESCRIPTION
**Pull request by ingridtv**
This PR includes:

- New image browser design with filtering/search options in a column on the left, and the image grid on the right. This way you can view the slides more easily while applying the filters/searching
- Added search bar to image browser. The search is a bit naive (checks whether the given string is in the name or the description of the slide), but may be helpful if the user knows what they are looking for
- Added option for filtering with general pathology tags
- Implemented logic for filtering/searching

### CODE REVIEW

**Comment by ingridtv** [comment]
Hey @UteSpiske!
Can you please test this functionality when you have time? If you have feedback on the layout/design I would be happy to hear that, too😊

**Review by UteSpiske — COMMENTED** [review]
I think the overall look of the image page is now much cleaner and easier to navigate, and the search bar is a great improvement for a large database.

I also think it would be useful to have a button that not only clears the search term, but also resets all the search parameters to their defaults. 

If the images are in 'list' view, changing the search parameters will only return the result in grid view. I think we should either remove the list view or change it so that if the list view is selected, then changes to the search parameters should also return the list view.

And when in list view, there is a part where you can click on 'Tasks* for a slide, but that only returns the grid view.

**Comment by ingridtv** [comment]
Great feedback, thanks! And the search/filtering seems to work as expected? I tried to fix all the bugs I could find when I was developing it, but I have a feeling we'll discover some bugs/inconsistencies that I've missed...

I also thought about a "clear all"/"reset" button -- I can give this a go and update here!

The list view has been kept from the early days of the project, but maybe it's time to let it go? If not, we should make sure it works👍

**Comment by ingridtv** [comment]
I added a 'Clear selection' button to the top of the sidebar. Will merge this now!

**Pull request merged**
