### PR TITLE
[Design] Improved workflow for making new tasks

### PR DESCRIPTION
**Pull request by ingridtv**
Implemented an improved workflow for creating new tasks. In this workflow the user

1. Selects a task type (e.g. multiple choice, short answer/paragraph)
2. Selects an image (whole slide image) that the task is about
3. Inputs task information and question
4. Annotates the slide

The user can go back and forth between these two steps.

There are still some highly needed improvements, but pushing this now as we want to get feedback. Some suggested tasks I will put on the To do-list:
- Hide radio buttons and style/format/highlight slide cards instead to see which image is selected
- If a task is generated from a slide, this slide should already be selected when making a task (the user should still double check and can change their selection if needed)
- Figure out whether to have a "previous" button to go back to task type/slide selection when the user has come this far. If the user goes back, the task information and annotations will be lost.

### CODE REVIEW

**Review by UteSpiske — COMMENTED** [review]
I think it is a great improvment to the last version in usability and design. 
Unfotunately the submit function doesn't work in the end of the pipeline

**Comment by ingridtv** [comment]
There was an error with the ID's of the forms that made the final form not submit. Seems to be working now

**Comment by ingridtv** [comment]
@UteSpiske Are you good with merging these changes? Is user friendliness "good enough" for our workshop/testing or should we fix some of of the aesthetics first?

**Comment by UteSpiske** [comment]
Nice that is now all working. 
I would remove the 'create new task' buttons in the images because they are not working at the moment and can be added in a further step.

**Comment by ingridtv** [comment]
Good point! I removed the buttons👍

I also added something that have fallen out - that tasks weren't automatically added to the course they were created from. Should be fixed with dbe4aaf

**Review by UteSpiske — APPROVED** [review]
I think it is now ready for merging

**Comment by ingridtv** [comment]
Etienne noted that filtering options/buttons are clickable in the image selection part of the workflow. But these aren't implemented and break the functionality.

Will remove this from the display for now, and put on the to do-list to add it.

**Comment by ingridtv** [comment]
I removed the filtering/search and added a TODO. Do you think it's alright for merging @etiennegaucher?

**Review by etiennegaucher — APPROVED** [review]

**Pull request merged**
